/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge26;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    /**
     * Code Challenge 26 Test
     */

    @Test
    public void insertionSortTest1() {

        int[] arr1 = {8, 4, 23, 42, 16, 15};

        InsertionSort insertionSort = new InsertionSort();
        insertionSort.insertionSort(arr1);
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(arr1));
    }


    @Test
    public void insertionSortTest2() {

        int[] arr2 = {20, 18, 12, 8, 5, -2};

        InsertionSort insertionSort = new InsertionSort();
        insertionSort.insertionSort(arr2);
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(arr2));

    }

    /**
     * Code Challenge 27 Test
     */

    @Test
    public void mergeSortTest1() {

        int[] mergeArr1 = {8, 4, 23, 42, 16, 15};

        MergeSort mergeSort = new MergeSort();
        mergeSort.mergeSort(mergeArr1);
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(mergeArr1));
    }

    @Test
    public void mergeSortTest2(){

        int [] mergeArr2 = {5, 12, 7, 5, 5, 7};

        MergeSort mergeSort = new MergeSort();
        mergeSort.mergeSort(mergeArr2);
        assertEquals("[5, 5, 5, 7, 7, 12]",Arrays.toString(mergeArr2));
    }


    @Test
    public void mergeSortTest3() {

        int[] mergeArr3 = {2};

        MergeSort mergeSort = new MergeSort();
        mergeSort.mergeSort(mergeArr3);
        assertEquals("[2]", Arrays.toString(mergeArr3));
    }

    /**
     * Code Challenge 28 Test
     */

    @Test
    public void quickSortTest1(){

        int[] quickSortArr1 = {8, 4, 23, 42, 16, 15};

        QuickSort quickSort = new QuickSort();
        quickSort.quickSort(quickSortArr1,0,5);
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(quickSortArr1));
    }

    @Test
    public void quickSortTest2(){

        int[] quickSortArr2 = {20, 18, 12, 8, 5, -2};

        QuickSort quickSort = new QuickSort();
        quickSort.quickSort(quickSortArr2,0,5);
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(quickSortArr2));
    }

    @Test
    public void quickSortTest3(){

        int[] quickSortArr3 = {5, 12, 7, 5, 5, 7};

        QuickSort quickSort = new QuickSort();
        quickSort.quickSort(quickSortArr3,0,5);
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(quickSortArr3));
    }

}
