/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge05;

import challenge05.structure.LinkedList;

public class App {

    public static void main(String[] args) {

        LinkedList linkedList = new LinkedList();
        linkedList.insert("M");
        linkedList.insert("O");
        linkedList.insert("H");
        linkedList.insert("A");
        linkedList.insert("M");
        linkedList.insert("M");
        linkedList.insert("A");
        linkedList.insert("D");

        System.out.println(linkedList);
        System.out.println(linkedList.include("M"));
        System.out.println(linkedList.include("N"));

    }
}
