/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge15;

import challenge15.structure.BinarySearchTree;
import challenge15.structure.KaryTree;


public class App {

    public static void main(String[] args) {

        /**
         *  Code Challenge 15
         */

        BinarySearchTree<Integer> binarySearchTree = new BinarySearchTree<>();

        binarySearchTree.add(23);
        binarySearchTree.add(8);
        binarySearchTree.add(42);
        binarySearchTree.add(4);
        binarySearchTree.add(16);
        binarySearchTree.add(27);
        binarySearchTree.add(85);

        System.out.println(binarySearchTree);

        System.out.println(binarySearchTree.contains(16));
        System.out.println(binarySearchTree.contains(10));
        System.out.println(binarySearchTree.contains(27));

        System.out.print("Depth First Traversal Pre-order => ");
        System.out.println(binarySearchTree.preOrder());
        System.out.print("Depth First Traversal In-order => ");
        System.out.println(binarySearchTree.inOrder());
        System.out.print("Depth First Traversal Post-order => ");
        System.out.println(binarySearchTree.postOrder());

        /**
         *  Code Challenge 16
         */

        System.out.print("The Maximum Value Of Binary Tree Is => ");
        System.out.println(binarySearchTree.treeMax());

        /**
         *  Code Challenge 17
         */

        System.out.print("Breadth First Traversal => ");
        System.out.println(binarySearchTree.breadthFirst(binarySearchTree));

        /**
         *  Code Challenge 18
         */

        KaryTree<Integer> KaryTree = new KaryTree<>(3);
        KaryTree.add(1);
        KaryTree.add(5);
        KaryTree.add(15);
        KaryTree.add(30);
        KaryTree.add(7);
        KaryTree.add(20);
        KaryTree.add(8);
        KaryTree.add(60);
        KaryTree.add(3);
        KaryTree.add(12);
        System.out.println(KaryTree);

        System.out.println(KaryTree.fizzBuzzTree(KaryTree));

        /**
         *  Code Challenge 19
         */

        System.out.println(binarySearchTree.sumOfOdd());
    }


}
