/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge30;

import org.junit.jupiter.api.Test;

import java.util.Objects;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

        /**
         * Code Challenge 30 Test
         */

        @Test
        public void hashTable(){
            HashTable<String, Integer> hashTableTest = new HashTable<>();

            hashTableTest.add("Mercedes", 20);
            hashTableTest.add("BMW", 40);
            hashTableTest.add("Toyota", 70);
            hashTableTest.add("Hyundai", 80);
            hashTableTest.add("Ford", 100);
            hashTableTest.remove("Hyundai");

            assertTrue(hashTableTest.contains("Toyota"));
            assertEquals(100, hashTableTest.get("Ford"));
            assertFalse(hashTableTest.contains("Hyundai"));
            assertNull(hashTableTest.get("Mazda"));
        }

        @Test
        public void collision(){
            System.out.println(Objects.hashCode("JS"));
            System.out.println(Objects.hashCode("Java"));

            HashTable<String, Integer> hashTableTest = new HashTable<>();

            hashTableTest.add("HTML",50);
            hashTableTest.add("CSS",60);
            hashTableTest.add("JS",70);
            hashTableTest.add("Java",90);

            assertTrue(hashTableTest.contains("JS"));
            assertTrue(hashTableTest.contains("Java"));
            assertEquals(70, hashTableTest.get("JS"));
            assertEquals(90, hashTableTest.get("Java"));

        }
        @Test
        public void successfullyRetrieveValue() {
            HashTable<String,Integer> hashTableTest = new HashTable<>();

            hashTableTest.add("JS",70);
            hashTableTest.add("Python",70);
            assertEquals(70, hashTableTest.get("JS"));

        }
}
