/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge10;

import challenge10.queue.structure.Queue;
import challenge10.stack.structure.Stack;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    /**
     *  Code Challenge 10 TEST
    */

    @Test
    public void pushToStackTest(){
        Stack stackTest = new Stack();

        stackTest.push("M");
        stackTest.push("O");
        stackTest.push("H");
        stackTest.push("A");

        assertEquals("Stack{top=StackNode{data='A', next=StackNode{data='H', next=StackNode{data='O', next=StackNode{data='M', next=null}}}}}", stackTest.toString());
    }

    @Test
    public void popStackTest(){
        Stack stackTest = new Stack();

        stackTest.push("M");
        stackTest.push("O");
        stackTest.push("H");
        stackTest.push("A");
        stackTest.pop();

        assertEquals("Stack{top=StackNode{data='H', next=StackNode{data='O', next=StackNode{data='M', next=null}}}}", stackTest.toString());
    }

    @Test
    public void emptyStackTest(){
        Stack stackTest = new Stack();

        stackTest.push("M");
        stackTest.push("O");
        stackTest.push("H");
        stackTest.pop();
        stackTest.pop();
        stackTest.pop();

        assertTrue(stackTest.isEmpty());
    }

    @Test
    public void peekStackTest(){
        Stack stackTest = new Stack();

        stackTest.push("M");
        stackTest.push("O");
        stackTest.push("H");

        assertEquals("H", stackTest.peek());

        stackTest.pop();
        assertEquals("O", stackTest.peek());
    }

    @Test
    public void enqueueToQueueTest(){
        Queue queueTest = new Queue();

        queueTest.enqueue("M");
        queueTest.enqueue("O");
        queueTest.enqueue("H");

        assertEquals("Queue{front=QueueNode{data='M', next=QueueNode{data='O', next=QueueNode{data='H', next=null}}}, rear=QueueNode{data='H', next=null}}", queueTest.toString());
    }

    @Test
    public void dequeueFromQueueTest(){
        Queue queueTest = new Queue();

        queueTest.enqueue("M");
        queueTest.enqueue("O");
        queueTest.enqueue("H");
        queueTest.dequeue();

        assertEquals("Queue{front=QueueNode{data='O', next=QueueNode{data='H', next=null}}, rear=QueueNode{data='H', next=null}}", queueTest.toString());
    }

    @Test
    public void emptyQueueTest(){
        Queue queueTest = new Queue();

        queueTest.enqueue("M");
        queueTest.enqueue("O");
        queueTest.enqueue("H");
        queueTest.dequeue();
        queueTest.dequeue();
        queueTest.dequeue();

        assertTrue(queueTest.isEmpty());
    }

    @Test
    public void peekQueueTest(){
        Queue queueTest = new Queue();

        queueTest.enqueue("M");
        queueTest.enqueue("O");
        queueTest.enqueue("H");

        assertEquals("M",queueTest.peek());

        queueTest.dequeue();
        assertEquals("O",queueTest.peek());
    }

    /**
     *  Code Challenge 11 TEST
     */

    @Test
    public void PseudoEnqueueTest() {
        PseudoQueue testPesudoQueue = new PseudoQueue();

        testPesudoQueue.enqueue("M");
        testPesudoQueue.enqueue("O");
        testPesudoQueue.enqueue("H");
        testPesudoQueue.enqueue("A");

        assertEquals("stack1=Stack{top=StackNode{data='A', next=StackNode{data='H', next=StackNode{data='O', next=StackNode{data='M', next=null}}}}}", testPesudoQueue.toString());
    }

    @Test
    public void PesudoDequeueTest(){
        PseudoQueue testPesudoQueue = new PseudoQueue();

        testPesudoQueue.enqueue("M");
        testPesudoQueue.enqueue("O");
        testPesudoQueue.enqueue("H");
        testPesudoQueue.enqueue("A");

        assertEquals("M", testPesudoQueue.dequeue());

        testPesudoQueue.dequeue();
        testPesudoQueue.dequeue();
        testPesudoQueue.dequeue();

        assertEquals("stack1=Stack{top=null}",testPesudoQueue.toString());
        assertEquals("Both Stacks Empty", testPesudoQueue.dequeue());
    }
}
