/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge35;

public class App {

    public static void main(String[] args) {

        /**
         * Code Challenge 35
         */

        Graph graph = new Graph();

        
    }
}
